import type { Metadata } from "next";

import styles from "./page.module.css";
import { TheatrePanel } from "@/components/ui/TheatrePanel";
import { Notice } from "@/components/System/Notice";
import { AddressRow } from "@/components/ui/AddressRow";
import {
  CHAIN_ID,
  CHAIN_NAME,
  HOOK_ADDRESS,
  POOL_MANAGER_ADDRESS,
  TOKEN_ADDRESS,
  TOKEN_SYMBOL,
} from "@/config/project";

export const metadata: Metadata = {
  title: "Docs",
  description:
    "How SHOWTIME is put together: the Uniswap V4 Hook, the pool, the data sources, and what this site will and will not claim.",
};

const SECTIONS = [
  { id: "overview", label: "Overview" },
  { id: "metaphor", label: "The metaphor" },
  { id: "hook", label: "The Hook" },
  { id: "data", label: "Data sources" },
  { id: "honesty", label: "What we won't claim" },
  { id: "addresses", label: "Addresses" },
  { id: "config", label: "Configuration" },
];

export default function DocsPage() {
  return (
    <article className={styles.page}>
      <header className={styles.head}>
        <span className="eyebrow">The programme</span>
        <h1 className="sectionTitle">Docs</h1>
        <p className="statement">READ BEFORE THE HOUSE LIGHTS DIM.</p>
      </header>

      <nav className={styles.toc} aria-label="On this page">
        {SECTIONS.map((s) => (
          <a key={s.id} href={`#${s.id}`} className={styles.tocLink}>
            {s.label}
          </a>
        ))}
      </nav>

      <div className={styles.article}>
        <section id="overview" className={styles.block}>
          <h2 className={styles.h2}>Overview</h2>
          <p className={styles.p}>
            SHOWTIME is a programmable Uniswap V4 Hook experiment on {CHAIN_NAME}.
            A Uniswap V4 pool nominates a Hook contract; the PoolManager then calls
            that contract at defined points in the pool&apos;s lifecycle. SHOWTIME
            uses that programmable layer for its fee and token mechanics.
          </p>
          <p className={styles.p}>
            This site is the front of house. It reads the chain, and where an
            indexer is configured it reads a cache of the chain. It does not
            simulate, estimate or extrapolate — if a number cannot be sourced, the
            page says so.
          </p>
        </section>

        <section id="metaphor" className={styles.block}>
          <h2 className={styles.h2}>The metaphor</h2>
          <div className={styles.tableWrap}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>On stage</th>
                  <th>In the protocol</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>The Big Top</td>
                  <td>The Uniswap V4 pool</td>
                </tr>
                <tr>
                  <td>The Ringmaster</td>
                  <td>The Hook contract</td>
                </tr>
                <tr>
                  <td>A ticket</td>
                  <td>A swap</td>
                </tr>
                <tr>
                  <td>Show revenue</td>
                  <td>Fees generated by pool activity</td>
                </tr>
                <tr>
                  <td>The performance</td>
                  <td>Programmable logic executed by the Hook</td>
                </tr>
                <tr>
                  <td>The final act</td>
                  <td>Tokens sent to a burn address</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className={styles.p}>
            The metaphor is how the site is organised. It is never a substitute
            for the mechanism — every claim about the mechanism has to come from
            the contract.
          </p>
        </section>

        <section id="hook" className={styles.block}>
          <h2 className={styles.h2}>The Hook</h2>
          <p className={styles.p}>
            Uniswap V4 introduced Hooks: contracts that a pool can call before and
            after initialisation, liquidity changes, swaps and donations. Which of
            those callbacks a hook may receive is encoded in the least significant
            bits of its deployed address, which is why V4 hooks are mined to a
            specific address prefix.
          </p>
          <h3 className={styles.h3}>The canonical callbacks</h3>
          <ul className={styles.list}>
            <li>
              <span className={styles.inline}>beforeInitialize</span> /{" "}
              <span className={styles.inline}>afterInitialize</span>
            </li>
            <li>
              <span className={styles.inline}>beforeAddLiquidity</span> /{" "}
              <span className={styles.inline}>afterAddLiquidity</span>
            </li>
            <li>
              <span className={styles.inline}>beforeRemoveLiquidity</span> /{" "}
              <span className={styles.inline}>afterRemoveLiquidity</span>
            </li>
            <li>
              <span className={styles.inline}>beforeSwap</span> /{" "}
              <span className={styles.inline}>afterSwap</span>
            </li>
            <li>
              <span className={styles.inline}>beforeDonate</span> /{" "}
              <span className={styles.inline}>afterDonate</span>
            </li>
          </ul>
          <p className={styles.p}>
            The site lists these names only to classify entries it finds in the
            installed ABI. It never asserts that SHOWTIME implements any of them.
          </p>
        </section>

        <section id="data" className={styles.block}>
          <h2 className={styles.h2}>Data sources</h2>
          <ul className={styles.list}>
            <li>
              <strong>Chain (source of truth).</strong> viem + wagmi read the token
              contract directly for supply, decimals, symbol and burn-sink
              balances.
            </li>
            <li>
              <strong>Alchemy.</strong> Asset transfers and block height, used for
              wallet history and burn transfers.
            </li>
            <li>
              <strong>Supabase (optional cache).</strong> Aggregated swap counts,
              fee events and burn events, populated by your own indexer. When it is
              absent the site shows{" "}
              <span className={styles.inline}>INDEXER OFFLINE</span> and keeps the
              chain-derived figures working.
            </li>
          </ul>
          <p className={styles.p}>
            All queries go through TanStack Query with a 30-second stale time and
            a 60-second refetch interval, so a busy page does not hammer your RPC
            quota.
          </p>
        </section>

        <section id="honesty" className={styles.block}>
          <h2 className={styles.h2}>What this site will not claim</h2>
          <Notice title="No invented contract behaviour" tone="calm">
            The Hook ABI file ships empty. Until a deployed artifact is installed,
            every Hook surface reads HOOK ABI NOT CONFIGURED, no Hook function is
            called, and no callback, permission or fee route is described.
          </Notice>
          <p className={`${styles.p} ${styles.afterNotice}`}>
            Likewise, the token ABI contains the EIP-20 standard interface only.
            Any project-specific function — a tax, a claim, a buyback trigger — is
            only real once it appears in the verified artifact.
          </p>
          <p className={styles.p}>
            Demo mode exists for development. When{" "}
            <span className={styles.inline}>NEXT_PUBLIC_DEMO_MODE=true</span>, a
            permanent DEMO SHOW banner is displayed and every sample value is
            tagged as such in the UI.
          </p>
        </section>

        <section id="addresses" className={styles.block}>
          <h2 className={styles.h2}>Addresses</h2>
          <TheatrePanel>
            <AddressRow name={`$${TOKEN_SYMBOL} token`} address={TOKEN_ADDRESS} isToken />
            <AddressRow name="SHOWTIME hook" address={HOOK_ADDRESS} />
            <AddressRow name="Pool manager" address={POOL_MANAGER_ADDRESS} />
          </TheatrePanel>
        </section>

        <section id="config" className={styles.block}>
          <h2 className={styles.h2}>Configuration</h2>
          <p className={styles.p}>
            Everything is read from environment variables and centralised in{" "}
            <span className={styles.inline}>src/config/project.ts</span>. Chain id
            is currently <span className={styles.inline}>{CHAIN_ID}</span> (
            {CHAIN_NAME}); there is no chain selector, by design.
          </p>
          <code className={styles.code}>{`NEXT_PUBLIC_CHAIN_ID=1
NEXT_PUBLIC_CHAIN_NAME=Ethereum Mainnet
NEXT_PUBLIC_RPC_URL=
NEXT_PUBLIC_ALCHEMY_API_KEY=
NEXT_PUBLIC_TOKEN_ADDRESS=
NEXT_PUBLIC_HOOK_ADDRESS=
NEXT_PUBLIC_POOL_MANAGER_ADDRESS=
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=
NEXT_PUBLIC_DEMO_MODE=false`}</code>
          <p className={styles.p}>
            See <span className={styles.inline}>README.md</span> for the full list,
            including the optional fee/burn description fields and the indexer
            lookback window.
          </p>
        </section>
      </div>
    </article>
  );
}
